version: '3.8'

services:
  backend:
    image: daniilsfirgers/node-web:development
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/server
      - ./backend/config.toml:/etc/server/config.toml
    depends_on:
        postgres:
          condition: service_healthy
    links:
      - "postgres:main_db"
    networks:
      custom-web:
        ipv4_address: 10.0.0.1
    dns: [8.8.8.8]

  postgres:
    image: daniilsfirgers/postgres-web:development
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d main"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      custom-web:
        ipv4_address: 10.0.0.2
    dns: [8.8.8.8]
    
    

volumes:
  postgres_data:

networks:
  custom-web:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/24