version: '3.8'

services:
  backend:
    image: daniilsfirgers/node-web:development
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/server
      - ./backend/config.toml:/etc/server/config.toml
    depends_on:
        postgres:
          condition: service_healthy

  postgres:
    image: daniilsfirgers/postgres-web:development
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d main"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: