name: Build and Push Docker development image

on:
  push:
    branches: [development]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Build and push Node Backend Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./backend
          file: ./backend/dev.node.Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_REGISTRY_USERNAME }}/node-web:development
          cache-to: type=gha,mode=max
          cache-from: type=gha

      - name: Build and push Postgres Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./backend
          file: ./backend/dev.postgres.Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_REGISTRY_USERNAME }}/postgres-web:development
          cache-to: type=gha,mode=max
          cache-from: type=gha
